server:
  port: 8085
 
spring:
  datasource:
        url: jdbc:mariadb://localhost:3306/test2
        username: root
        password: 
        driver-class-name: org.mariadb.jdbc.Driver
        
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  thymeleaf:
    prefix: classpath:/static/html/
    mode: LEGACYHTML5
